### ISSUE TITLE
Plugin collision

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-indie-cite#1]
<a href="https://github.com/pfefferle/wordpress-cite/issues" class="u-in-reply-to"></a>Plugin collision

This plugin has a naming collision with https://wordpress.org/plugins/cite/ which has slightly different functionality.

**Comment by pfefferle** [comment]
Do you think this is a problem? I haven't planned to upload it to the WordPress directory, so I thought it doesn't matter.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/pfefferle/wordpress-cite/issues/1#issuecomment-219301380" class="u-in-reply-to"></a>As it's not in the WordPress directory, it won't matter too much.  For those who do try it out however, the existing one that is in the WP directory has a higher version number and so WP will automatically prompt them to update it. The unsuspecting novices who aren't paying attention will likely blindly update and thereby completely override the plugin with a separate piece of code and functionality. Something to be aware of from a UX perspective if you hadn't noticed. #CaveatEmptor

**Comment by pfefferle** [comment]
i renamed the plugin!
