### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by metbril** [pfefferle/wordpress-indie-cite#3]
Nice plugin. I'd like to have the plugin (although tiny, it's mostly 1 string) translated in Dutch, without manually editing it. How difficult is it to add translation files? The translation for 'short link' can be copied from the Hum plugin.

My other 2 options are to:

- hard change to source code 
- Use somthing like https://wordpress.org/plugins/loco-translate/ locally

**Comment by pfefferle** [comment]
It is already prepared... I will generate a POT file and then you simply have to place the sources (.po and .mo file) besides the POT file.
